const  ActionType = {
    // Login action types
    LOGIN_ERROR: 'LOGIN_ERROR',
    PASSWORD_ERROR: 'PASSWORD_ERROR',
    OPERATION_INPROGRESS: 'OPERATION_INPROGRESS',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    RESET_SUCCESS: 'RESET_SUCCESS',
    LOGOUT: 'LOGOUT',
};

export default ActionType;